GET http://localhost:8080/webapi/libros


#######

GET http://localhost:8080/webapi/libros?titulo=el camino perfecto

#######

GET http://localhost:8080/webapi/libros?autor=juan

#######

POST http://localhost:8080/webapi/libros
content-type: application/json

{
    "isbn": "SSSS09",
    "titulo": "lA NIÑA BONITA",
    "autor":"Salomé S",
    "paginas":500
}
######
DELETE http://localhost:8080/webapi/libros/1144C

#######

POST http://localhost:8080/webapi/libros
content-type: application/json

{
    "isbn": "C789",
    "titulo": "El garabato",
    "autor":"Juan",
    "paginas":300
}

######

GET http://localhost:8080/webapi/libros/A123

######
GET http://localhost:8080/webapi/libros/paginado

